apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    apps: 3tier-app
spec:
  type: NodePort
  ports:
  - name: tcp-4000-34000
    nodePort: 31082
    port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    app: 3tier-app
