apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    apps: 3tier-app
spec:
  type: NodePort
  ports:
  - name: tcp-31081-5000
    nodePort: 31081
    port: 3000
    protocol: TCP
  selector:
    app: 3tier-app
